name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master
    
    - name: Run fmt and ast-check
      run: |
        zig fmt src --ast-check --check
        zig fmt examples --ast-check --check

    - name: Run tests
      run: |
        zig build test

